# About this notebook
This notebook takes the mission assignments file and merges it with the LLM generated SoW list.  This notebook must be run prior to using the SoW topics notebook as it generates the llm_ma_merge and filtered_topics csv files.

In [2]:
import pandas as pd

# Merge the LLM output with the original mission assignments dataset

In [3]:
df_MA = pd.read_csv('MissionAssignments.csv')

In [4]:
len(df_MA)

40475

In [4]:
#import the file generated by LLM
df_llm=pd.read_csv('actions_topics_bedrock_full_sow.csv')

In [5]:
#len(df_llm)

10477

In [9]:
combined_df=pd.merge(df_llm,df_MA,how='left',on='statementOfWork')

In [10]:
#len(combined_df)

45067

In [12]:
combined_df.to_csv('llm_MA_merge.csv')

# Create csv file with the topics filtered

In [14]:
reduced=combined_df[['maId','clean_statement_topic','declarationType','maAmendNumber','supportFunction']]

In [16]:
filtered=reduced[(reduced['declarationType']!='SU')&(reduced['maAmendNumber']==0)&(reduced['supportFunction']<=15)]

In [17]:
len(filtered)

7918

In [29]:
top_list=filtered['clean_statement_topic'].unique().tolist()

In [31]:
#len(top_list)

993

In [23]:
filtered.dropna(inplace=True)

C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\3450873322.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered.dropna(inplace=True)

In [28]:
filtered.head()

,maId,clean_statement_topic,declarationType,maAmendNumber,supportFunction
0,3612EMCTDOI-USGS01,flood monitoring and data collection,EM,0,5.0
10,4856DRCAUSDA-APH01,personnel support,DR,0,11.0
16,4795DRNMDOT01,personnel support,DR,0,1.0
18,3614EMLADOT01,personnel support,EM,0,1.0
31,3614EMLADOJ-ATF01,personnel support,EM,0,13.0

In [26]:
filtered.to_csv('filtered_topics.csv')

# Combined AR and filtered topic csv generation
This was not used in the final model, but the code is preserved as it may be useful for future analysis and updates.

In [32]:
filtered['sow_top_num']=0

C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\601769210.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num']=0

In [35]:
filtered.head()

,index,maId,clean_statement_topic,declarationType,maAmendNumber,supportFunction,sow_top_num
0,0,3612EMCTDOI-USGS01,flood monitoring and data collection,EM,0,5.0,0
1,10,4856DRCAUSDA-APH01,personnel support,DR,0,11.0,0
2,16,4795DRNMDOT01,personnel support,DR,0,1.0,0
3,18,3614EMLADOT01,personnel support,EM,0,1.0,0
4,31,3614EMLADOJ-ATF01,personnel support,EM,0,13.0,0

In [34]:
filtered.reset_index(inplace=True)

In [39]:
for i in range(len(filtered)):
    if filtered['clean_statement_topic'].iloc[i] in top_list:
        filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])

C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  filtered['sow_top_num'].iloc[i]=top_list.index(filtered['clean_statement_topic'].iloc[i])
C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2597315705.py:3: SettingWithCopyWarning:

In [41]:
filtered.head(20)

,index,maId,clean_statement_topic,declarationType,maAmendNumber,supportFunction,sow_top_num
0,0,3612EMCTDOI-USGS01,flood monitoring and data collection,EM,0,5.0,0
1,10,4856DRCAUSDA-APH01,personnel support,DR,0,11.0,1
2,16,4795DRNMDOT01,personnel support,DR,0,1.0,1
3,18,3614EMLADOT01,personnel support,EM,0,1.0,1
4,31,3614EMLADOJ-ATF01,personnel support,EM,0,13.0,1
5,35,4856DRCADOJ-ATF01,personnel support,DR,0,13.0,1
6,49,3614EMLADOE-OE02,energy support operations,EM,0,12.0,2
7,51,3621EMVADOE-OE01,energy support operations,EM,0,12.0,2
8,56,4856DRCADOE-OE01,energy support operations,DR,0,12.0,2
9,57,3624EMKYDOE-OE01,energy support operations,EM,0,12.0,2
10,59,4860DRKYDOE-OE01,energy support operations,DR,0,12.0,2
11,68,4806DRFLDOT01,personnel deployment,DR,0,1.0,3
12,72,4806DRFLDOD-OPS01,military coordination support,DR,0,0.0,4
13,85,4382DRCAFPS01,facility security,DR,0,13.0,5
14,92,3609EMVTDOJ-ATF02,urban search and rescue deployment,EM,0,13.0,6
15,97,3609EMVTDOJ-ATF01,personnel support,EM,0,13.0,1
16,99,4795DRNMDOJ-ATF01,personnel support,DR,0,13.0,1
17,108,4788DRARCOE-SWD01,disaster response personnel support,DR,0,3.0,7
18,112,4843DRNMCOE-SPD01,disaster response personnel support,DR,0,3.0,7
19,115,3614EMLAHHS-ASPR01,personnel support,EM,0,8.0,1

In [42]:
export=filtered[['maId','sow_top_num']]

In [43]:
export.to_csv('SoW_topic_numbers.csv')

In [45]:
topics_and_nums=filtered[['clean_statement_topic','sow_top_num']]
topics_and_nums.drop_duplicates(inplace=True)

C:\Users\sbpow\AppData\Local\Temp\ipykernel_26000\2512720977.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  topics_and_nums.drop_duplicates(inplace=True)

In [48]:
len(export)

6250

In [47]:
topics_and_nums.to_csv('sow_topics_with_nums.csv')

In [49]:
AR_df=pd.read_csv('AR_topics.csv')

In [53]:
combined_topics=pd.merge(export,AR_df,how='left',on='maId')

In [54]:
len(combined_topics)

6250

In [55]:
combined_topics.head()

,maId,sow_top_num,Unnamed: 0,assistanceRequested,AR_topic
0,3612EMCTDOI-USGS01,0,0,USGS Field measurements of flood-water heights...,28
1,4856DRCAUSDA-APH01,1,30014,"USDA liaison(s) to the RRCC, IOF, JFO, or othe...",37
2,4795DRNMDOT01,1,343,"Activate DOT to RRCC and virtually IOF, JFO, o...",80
3,3614EMLADOT01,1,27960,This is a re-issue of SU-LA-24090902-DOT-01 fo...,24
4,3614EMLADOJ-ATF01,1,27940,"This MA replaces MA# 1509-477504, LA24090902DO...",32

In [56]:
combined_export=combined_topics[['maId','sow_top_num','AR_topic']]

In [57]:
combined_export.to_csv('sow_AR_top_nums.csv')